plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
hostnames:
  - private-dns-name
keyed_groups: # This will create groups like k8s_control_plane, k8s_node
  - key: tags.type
    prefix: k8s
    separator: "_"


